---
target: ath79/generic
brand_nice: Xiaomi
model_nice: AIoT AC2350
version_nice: v1

# TODO
dsa_ports:
  - lan1
  - lan2
  - lan3
  - wan

wireless_devices:
  - name: 11a_standard
    band: 5g
    htmode_prefix: VHT
    path: pci0000:00/0000:00:00.0
    ifname_hint: wlan5
  - name: 11g_standard
    band: 2g
    htmode_prefix: HT
    path: platform/ahb/18100000.wmac
    ifname_hint: wlan2
